### ISSUE TITLE
[FEATURE] Login REST API

### ISSUE THREAD

**Issue by Wizdave97** [BuildForSDG/farmify#4]
# Login REST API

An API to handle user authentication requests using JWT

**Comment by chineduprincewill** [comment]
JWT not being received in response yet

**Comment by chineduprincewill** [comment]
Return status as one of the values in user object being returned on login

**Comment by Wizdave97** [comment]
> JWT not being received in response yet

JWT is inside an httpOnly cookie, you won't see it, just make sure on successful login request you give the user an authentication state that is positive and send any further requests to roots that require authentication with credentials enabled. The httpOnly cookie will be automatically sent.
